### PR TITLE
Added JOSS paper

### PR DESCRIPTION
**Pull request by kbg**
The text @mbobra and I wrote, to be submitted to [JOSS](https://joss.theoj.org/).

- Preview of the current version: [paper.pdf](https://github.com/sunpy/drms/files/3372879/paper.pdf)
- The plan is to submit on Monday. Please check your name, affiliation and ORCID.
- Note: I will clean up and rebase this branch before I will merge it into master.

Before merging this into the main:

- [x]  Remove JOSS logo, LaTeX template and Makefile
- [ ]  Rebase/squash commits to avoid having more than one figure version in the history

### CODE REVIEW

**Comment by kbg** [comment]
A preview of the current version: [paper.pdf](https://github.com/sunpy/drms/files/3360574/paper.pdf)

**Comment by nitinkgp23** [comment]
Just a small issue.. My zip code is 721302 .(2 is missing).

**Comment by kbg** [comment]
> Just a small issue.. My zip code is 721302 .(2 is missing).

Thanks, @nitinkgp23, I'll fix it later.

Do you have an ORCID? If not: It's easy to [register](https://orcid.org/register). You don't have to add much personal data. You can just sign up to get an ID and keep everything else private (except your name and ORCID).

**Comment by nitinkgp23** [comment]
Thanks @kbg . I just registered for an ORCID. 

https://orcid.org/0000-0001-6915-4583

**Comment by kbg** [comment]
Great, thanks. I'll also add this to the document later.

**Comment by mbobra** [comment]
A small issue: Everyone else's address has a zip code, so @kbg if you want to add one to yours that might make everything look more consistent. 

In any case, I am happy with this -- so feel free to submit anytime!

**Pull request merged**
